# Generated by Django 3.0.14 on 2022-02-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220209_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Type',
            new_name='EventType',
        ),
    ]
