# Generated by Django 3.0.14 on 2022-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0003_auto_20220209_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
