# Generated by Django 3.0.14 on 2022-02-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(
                default=None, related_name='event', to='home.Tag'),
        ),
        migrations.AddField(
            model_name='links',
            name='tag',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='home.Tag'),
            preserve_default=False,
        ),
    ]
