# Generated by Django 3.0.14 on 2022-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0006_allsections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AddField(
            model_name='people',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='people', to='home.Tag'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
