# Generated by Django 3.0.14 on 2022-02-12 20:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0007_auto_20220212_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mission', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='files_attachment',
        ),
        migrations.RemoveField(
            model_name='people',
            name='social_links',
        ),
        migrations.AddField(
            model_name='event',
            name='documents_links',
            field=models.ManyToManyField(default=None, related_name='event', to='home.Links'),
        ),
        migrations.AddField(
            model_name='people',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='people',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup_initiative',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
