# Generated by Django 3.0.14 on 2022-02-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0010_auto_20220212_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='home.Tag'),
        ),
    ]
