# Generated by Django 3.0.14 on 2022-02-13 05:51

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0011_auto_20220212_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='batch',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1984), home.models.max_value_current_year], verbose_name='year'),
        ),
    ]
