# Generated by Django 3.0.14 on 2022-02-13 05:57

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0012_auto_20220213_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='Rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='batch',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1998), home.models.max_value_current_year], verbose_name='year'),
        ),
    ]
