# Generated by Django 3.0.14 on 2022-02-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220213_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='documents_links',
            field=models.ManyToManyField(blank=True, null=True, related_name='event', to='home.Links'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='event', to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='links',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='home.Tag'),
        ),
    ]
