# Generated by Django 3.0.14 on 2022-02-14 17:19

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0014_auto_20220213_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, limit_choices_to=home.models.Event.limit_event_type_choices, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='home.Tag'),
        ),
    ]
