# Generated by Django 3.0.14 on 2022-02-14 17:52

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0015_auto_20220214_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to=home.models.Event.limit_tags_choices, null=True, related_name='event', to='home.Tag'),
        ),
        migrations.AlterField(
            model_name='people',
            name='tags',
            field=models.ManyToManyField(default=None, limit_choices_to=home.models.People.limit_tags_choices, related_name='people', to='home.Tag'),
        ),
    ]
