# Generated by Django 3.0.14 on 2022-02-19 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('home', '0017_auto_20220219_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
